name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          pipx install poetry
          poetry --version

      - name: Install dependencies
        run: poetry install

      - name: Create Version File
        run: |
          $version = $env:GITHUB_REF -replace "refs/tags/v", ""
          echo "Number=$version" > version.txt
          echo "Creating build for version $version"

      - name: Analysing the code with pylint
        run: |
          poetry run pylint src --disable=C0114,C0115,C0116,C0303,C0206,R0903,R0914,R1702,W0212,W0611,W0612,W0702,E0401 || true

      - name: Build with PyInstaller
        run: |
          poetry run pyinstaller build.spec

      - name: Install Inno Setup
        run: |
          choco install innosetup -y

      - name: Compile Installer with Inno Setup
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" setup_script.iss

      - name: Calculate SHA256
        id: sha256
        run: |
          $hash = (Get-FileHash -Path "Output\StayOnTrack_Setup_v*.exe" -Algorithm SHA256).Hash
          echo "INSTALLER_SHA256=$hash" >> $env:GITHUB_OUTPUT
          echo "SHA256: $hash"

      - name: Upload Binary to Release
        uses: softprops/action-gh-release@v1
        with:
          files: Output/StayOnTrack_Setup_v*.exe
          body: |
            ### SHA256 Checksum
            ```
            ${{ steps.sha256.outputs.INSTALLER_SHA256 }}
            ```
            append_body: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
